spring.datasource.url=jdbc:postgresql://localhost:5432/medicoes
spring.datasource.username=medicoes_user
spring.datasource.password=medicoes_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true

spring.flyway.clean-disabled=false