version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: medicoes-postgres
    restart: always
    environment:
      POSTGRES_DB: medicoes
      POSTGRES_USER: medicoes_user
      POSTGRES_PASSWORD: medicoes_pass
    ports:
      - "5432:5432"
    volumes:
      - medicoes-postgres-data:/var/lib/postgresql/data

volumes:
  medicoes-postgres-data: